import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { urbanist } from "./fonts";

export const metadata: Metadata = {
  title: "Mahima's Portfolio",
  description: "Generated by Mahima",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
